// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAgency.Client;

namespace Assicurazione.Migrations
{
    [DbContext(typeof(ClientiContext))]
    [Migration("20210903104307_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TravelAgency.Clienti", b =>
                {
                    b.Property<int>("IdClienti")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodFiscale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolizzeId")
                        .HasColumnType("int");

                    b.HasKey("IdClienti");

                    b.HasIndex("PolizzeId");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("TravelAgency.Polizze", b =>
                {
                    b.Property<int>("IdPolizze")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataScadenza")
                        .HasColumnType("datetime2");

                    b.Property<int>("NPolizza")
                        .HasColumnType("int");

                    b.Property<int>("RataMensile")
                        .HasColumnType("int");

                    b.Property<int>("TipoPolizza")
                        .HasColumnType("int");

                    b.HasKey("IdPolizze");

                    b.ToTable("Polizze");
                });

            modelBuilder.Entity("TravelAgency.Clienti", b =>
                {
                    b.HasOne("TravelAgency.Polizze", "Polizze")
                        .WithMany()
                        .HasForeignKey("PolizzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polizze");
                });
#pragma warning restore 612, 618
        }
    }
}
